import type { NextPage } from "next";
import Head from "next/head";
import { Button, Form, Input, InputGroup } from "react-daisyui";
import { useForm } from "react-hook-form";
const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();
  const onSubmit = (data) => console.log(data);
  return (
    <>
      <Head>
        <title>Half Asleep</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center gap-6 p-4">
        <h3 className=" text-xl">Join a session</h3>
        <Form
          onSubmit={handleSubmit(onSubmit)}
          className="flex w-1/3 flex-col gap-4"
        >
          <div>
            <Form.Label title="Name"></Form.Label>
            <Input
              {...register("name", { required: true })}
              placeholder="Your display name"
              className="w-full"
            />
            {errors.name && (
              <span className="text-red-500">This field is required</span>
            )}
          </div>
          <div>
            <Form.Label title="Contact info"></Form.Label>
            <Input
              {...register("contactInfo", { required: true })}
              placeholder="Any old shit"
              className="w-full"
            />
            {errors.contactInfo && (
              <span className="text-red-500">This field is required</span>
            )}
          </div>
          <Button type="submit" color="primary">
            Join Session
          </Button>
        </Form>
      </main>
    </>
  );
};

export default Home;
